config/routes.rb
Rails.application.routes.draw do

  get 'acknowledgements' => 'pages#show', :page => 'acknowledgements'
  get 'bibliography' => 'pages#show', :page => 'bibliography'
  get 'contact' => 'pages#show', :page => 'contact'
  get 'cv' => 'pages#show', :page => 'cv'
  get 'dictionary' => 'pages#show', :page => 'dictionarys'
  get 'map' => 'pages#show', :page => 'map'
  get 'overview' => 'pages#show', :page => 'overview'
  get 'prosopography' => 'pages#show', :page => 'prosopography'
  get 'praxis' => 'pages#show', :page => 'praxis'
  get 'preface' => 'pages#show', :page => 'preface'
  get 'contact' => 'pages#show', :page => 'contact'
  get 'cite' => 'pages#show', :page => 'cite'
  get 'project-team' => 'pages#show', :page => 'project-team'

  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destory'

  get 'authors' => 'authors#index'
  get 'authors/edit' => 'authors#editlist'
  get 'authors/:id/edit' => 'authors#edit'

  get 'texts/search' => 'texts#search'
  post 'texts/search' => 'texts#search'

  get 'texts/searchpages' => 'texts#searchpages'

  get 'texts/:id/structure' => 'texts#structure'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy'

  get 'edit' => 'edit#index'

  resources :languages
  resources :texts do
    get 'read', on: :member
  end
  resources :authors
  resources :orthographies
  resources :text_categories, :path => '/categories'
  resources :missionary_groups, :path => '/groups'
  resources :publishers

  root :to => 'pages#home'

end

app/models/author.rb
class Author < ActiveRecord::Base
  has_and_belongs_to_many :texts

  def full_name
    full = last
    if first
      full = full + ', ' + first
    end
    return full
  end

end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :require_login

  def index
    @authors = Author.order('last ASC').where(nil)
  end

  def new
    @author = Author.new
    render 'edit'
  end

  def create
    @author = Author.new()
    if @author.save
      @author.update_attributes(author_params)
      flash[:author_id] = @author.id
      redirect_to controller: 'authors', action: 'editlist'
    else
      render :action => 'new'
    end
  end

  def destroy
    Author.find(params[:id]).destroy
    flash[:success] = 'author deleted'
    redirect_to controller: 'authors', action: 'index'
  end

  def show
    @author = Author.find(params[:id])
  end

  def typeahead
    @authors = Author.where('upper(last) like ?', '#{params[:q]}%'.upcase)
    render json: @authors
  end

  def edit
    @author = Author.find(params[:id])
  end

  def editlist
    @authors = Author.order('last ASC').where(nil)
  end

  def update
    @author = Author.find(params[:id])
    @author.update_attributes(author_params)
    redirect_to action: :show, id: @author.id
  end

  def author_params
    params.require(:author).permit(:last, :first)
  end
end

app/helpers/authors_helper.rb
module AuthorsHelper
  def form_line(form, field, input_type)
    render "texts/form_line", form: form, field: field, input_type: input_type
  end
end

app/views/authors/edit.html.erb
<div class="text">
  <div class="metadata">

    <h3>Author</h3>
    <%= form_for @author do |f| %>
        <dl>
          <dt>Last</dt>
          <dd><%= f.text_field(:last) %></dd>

          <dt>First</dt>
          <dd><%= f.text_field(:first) %></dd>

        </dl>
        <%= submit_tag("Update") %>
    <% end %>
  </div>
</div>

app/views/authors/editlist.erb
<h1>Authors</h1>

<ul>
  <% @authors.each do |author| %>
      <li><%= link_to author.full_name, controller: "authors", action: "edit", id: author.id %>
        <%= link_to 'delete', author_path(author.id), :method => :delete, :class => 'delete', :confirm => 'Are you sure ?' %>
      </li>
  <% end %>
</ul>
<%= link_to '+ New author', :controller => :authors, :action => "new" %>

app/views/authors/index.html.erb
<h1>Authors</h1>

<ul>
  <% @authors.each do |author| %>
      <li><%= link_to author.full_name, controller: "authors", action: "edit", id: author.id %>
        <%= link_to 'delete', author_path(author.id), :method => :delete, :class => 'delete', :confirm => 'Are you sure ?' %>
      </li>
  <% end %>
</ul>
<%= link_to '+ New author', :controller => :authors, :action => "new" %>

app/views/authors/search.html.erb
<ul>
  <% @authors.each do |author| %>
      <li><a href="/authors/<%= author.id %>"><%= author.full_name %></a></li>
  <% end %>
</ul>

app/views/authors/show.html.erb
<h2><%= @author.full_name %></h2>
<% if logged_in? %>
    <%= link_to_if(logged_in?, "Edit", [:edit, @author]) %>
<% end %>
<ul>
  <% @author.texts.each do |text| %>
      <li><%= link_to text.title, text_path(text) %></li>
  <% end %>
</ul>