config/routes.rb
Rails.application.routes.draw do

  get 'acknowledgements' => 'pages#show', :page => 'acknowledgements'
  get 'bibliography' => 'pages#show', :page => 'bibliography'
  get 'contact' => 'pages#show', :page => 'contact'
  get 'cv' => 'pages#show', :page => 'cv'
  get 'dictionary' => 'pages#show', :page => 'dictionarys'
  get 'map' => 'pages#show', :page => 'map'
  get 'overview' => 'pages#show', :page => 'overview'
  get 'prosopography' => 'pages#show', :page => 'prosopography'
  get 'praxis' => 'pages#show', :page => 'praxis'
  get 'preface' => 'pages#show', :page => 'preface'
  get 'contact' => 'pages#show', :page => 'contact'
  get 'cite' => 'pages#show', :page => 'cite'
  get 'project-team' => 'pages#show', :page => 'project-team'

  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destory'

  get 'authors' => 'authors#index'
  get 'authors/edit' => 'authors#editlist'
  get 'authors/:id/edit' => 'authors#edit'

  get 'texts/search' => 'texts#search'
  post 'texts/search' => 'texts#search'

  get 'texts/searchpages' => 'texts#searchpages'

  get 'texts/:id/structure' => 'texts#structure'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy'

  get 'edit' => 'edit#index'

  resources :languages
  resources :texts do
    get 'read', on: :member
  end
  resources :authors
  resources :orthographies
  resources :text_categories, :path => '/categories'
  resources :missionary_groups, :path => '/groups'
  resources :publishers

  root :to => 'pages#home'

end

app/models/text_category.rb
class TextCategory < ActiveRecord::Base
  has_many :texts
end

app/controllers/text_categories_controller.rb
class TextCategoriesController < ApplicationController
  before_action :require_login
  
  def new
    @text_category = TextCategory.new
    render 'edit'
  end

  def create
    @text_category = TextCategory.new()
    if @text_category.save
      @text_category.update_attributes(text_category_params)
      flash[:orgthography_id] = @text_category.id
      redirect_to controller: 'text_categories', action: 'index'
    else
      render :action => 'new'
    end
  end

  def destroy
    TextCategory.find(params[:id]).destroy
    flash[:success] = 'TextCategory deleted'
    redirect_to controller: 'text_categories', action: 'index'
  end
  
  def index
    @categories = TextCategory.order('name ASC').where(nil)
  end

  def edit
    @text_category = TextCategory.find(params[:id])
  end

  def update
    @category = TextCategory.find(params[:id])
    @category.update_attributes(text_category_params)
    redirect_to action: :index
  end

  def text_category_params
    params.require(:text_category).permit(:name)
  end
end

app/helpers/text_categories_helper.rb
module TextCategoriesHelper
end

app/views/text_categories/create.html.erb
<h1>TextCategory#create</h1>
<p>Find me in app/views/text_category/create.html.erb</p>

app/views/text_categories/destroy.html.erb
<h1>TextCategory#destroy</h1>
<p>Find me in app/views/text_category/destroy.html.erb</p>

app/views/text_categories/edit.html.erb
<div class="text">
  <div class="metadata">
    <h3>Text category</h3>
    <%= simple_form_for @text_category do |f| %>
        <%= f.input :name, :as => :string %>
        <%= f.submit 'Save' %>
    <% end %>
  </div>
</div>

app/views/text_categories/index.html.erb
<h2>Text categories</h2>
<ul>
  <% @categories.each do |category| %>
      <li><%= link_to category.name, controller: "text_categories", action: "edit", id: category.id %>
        <%= link_to 'delete', text_category_path(category.id), :method => :delete, :class => 'delete', :confirm => 'Are you sure ?' %>
      </li>
  <% end %>
</ul>

<%= link_to '+ New category', :controller => :text_categories, :action => :new %>

app/views/text_categories/update.html.erb
<h1>TextCategory#update</h1>
<p>Find me in app/views/text_category/update.html.erb</p>