config/routes.rb
Rails.application.routes.draw do

  get 'acknowledgements' => 'pages#show', :page => 'acknowledgements'
  get 'bibliography' => 'pages#show', :page => 'bibliography'
  get 'contact' => 'pages#show', :page => 'contact'
  get 'cv' => 'pages#show', :page => 'cv'
  get 'dictionary' => 'pages#show', :page => 'dictionarys'
  get 'map' => 'pages#show', :page => 'map'
  get 'overview' => 'pages#show', :page => 'overview'
  get 'prosopography' => 'pages#show', :page => 'prosopography'
  get 'praxis' => 'pages#show', :page => 'praxis'
  get 'preface' => 'pages#show', :page => 'preface'
  get 'contact' => 'pages#show', :page => 'contact'
  get 'cite' => 'pages#show', :page => 'cite'
  get 'project-team' => 'pages#show', :page => 'project-team'

  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destory'

  get 'authors' => 'authors#index'
  get 'authors/edit' => 'authors#editlist'
  get 'authors/:id/edit' => 'authors#edit'

  get 'texts/search' => 'texts#search'
  post 'texts/search' => 'texts#search'

  get 'texts/searchpages' => 'texts#searchpages'

  get 'texts/:id/structure' => 'texts#structure'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy'

  get 'edit' => 'edit#index'

  resources :languages
  resources :texts do
    get 'read', on: :member
  end
  resources :authors
  resources :orthographies
  resources :text_categories, :path => '/categories'
  resources :missionary_groups, :path => '/groups'
  resources :publishers

  root :to => 'pages#home'

end

app/models/publisher.rb
class Publisher < ActiveRecord::Base
  has_many :texts
end

app/controllers/publishers_controller.rb
class PublishersController < ApplicationController

  before_action :require_login

  def new
    @publisher = Publisher.new
    render "edit"
  end

  def create
    @publisher = Publisher.new()
    if @publisher.save
      @publisher.update_attributes(publisher_params)
      flash[:orgthography_id] = @publisher.id
      redirect_to controller: "publishers", action: 'index'
    else
      render :action => "new"
    end
  end

  def destroy
    Publisher.find(params[:id]).destroy
    flash[:success] = "Publisher deleted"
    redirect_to controller: "publishers", action: 'index'
  end

  def index
      @publishers = Publisher.order('name ASC').where(nil)
  end

  def edit
    @publisher = Publisher.find(params[:id])
  end

  def update
    @publisher = Publisher.find(params[:id])
    @publisher.update_attributes(publisher_params)
    redirect_to action: :index
  end

  def publisher_params
    params.require(:publisher).permit(:name)
  end

  def require_login
    unless logged_in?
      redirect_to controller: "texts", action: 'index'
    end
  end
end

app/helpers/publishers_helper.rb
module PublishersHelper
end

app/views/publishers/create.html.erb
<h1>Publishers#create</h1>
<p>Find me in app/views/publishers/create.html.erb</p>

app/views/publishers/destroy.html.erb
<h1>Publishers#destroy</h1>
<p>Find me in app/views/publishers/destroy.html.erb</p>

app/views/publishers/edit.html.erb
<div class="text">
  <div class="metadata">
    <h2>Publisher</h2>
    <%= simple_form_for @publisher do |f| %>
        <%= f.input :name, :as => :string %>
        <%= f.submit 'Save' %>
    <% end %>
  </div>
</div>

app/views/publishers/index.html.erb
<h2>Publishers</h2>
<ul>
  <% @publishers.each do |publisher| %>
      <li>
        <%= link_to publisher.name, controller: "publishers", action: "edit", id: publisher.id %>
        <%= link_to 'delete', publisher_path(publisher.id), :method => :delete, :class => 'delete', :confirm => 'Are you sure ?' %>
      </li>
  <% end %>
</ul>
<%= link_to '+ New publisher', :controller => :publishers, :action => :new %>

app/views/publishers/update.html.erb
<h1>Publishers#update</h1>
<p>Find me in app/views/publishers/update.html.erb</p>