config/routes.rb
Rails.application.routes.draw do

  get 'acknowledgements' => 'pages#show', :page => 'acknowledgements'
  get 'bibliography' => 'pages#show', :page => 'bibliography'
  get 'contact' => 'pages#show', :page => 'contact'
  get 'cv' => 'pages#show', :page => 'cv'
  get 'dictionary' => 'pages#show', :page => 'dictionarys'
  get 'map' => 'pages#show', :page => 'map'
  get 'overview' => 'pages#show', :page => 'overview'
  get 'prosopography' => 'pages#show', :page => 'prosopography'
  get 'praxis' => 'pages#show', :page => 'praxis'
  get 'preface' => 'pages#show', :page => 'preface'
  get 'contact' => 'pages#show', :page => 'contact'
  get 'cite' => 'pages#show', :page => 'cite'
  get 'project-team' => 'pages#show', :page => 'project-team'

  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destory'

  get 'authors' => 'authors#index'
  get 'authors/edit' => 'authors#editlist'
  get 'authors/:id/edit' => 'authors#edit'

  get 'texts/search' => 'texts#search'
  post 'texts/search' => 'texts#search'

  get 'texts/searchpages' => 'texts#searchpages'

  get 'texts/:id/structure' => 'texts#structure'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy'

  get 'edit' => 'edit#index'

  resources :languages
  resources :texts do
    get 'read', on: :member
  end
  resources :authors
  resources :orthographies
  resources :text_categories, :path => '/categories'
  resources :missionary_groups, :path => '/groups'
  resources :publishers

  root :to => 'pages#home'

end

app/models/text.rb
class Text < ActiveRecord::Base
  has_and_belongs_to_many :authors
  has_and_belongs_to_many :publishers
  belongs_to :missionary_group
  belongs_to :text_category
  has_many :languages_texts
  has_many :languages, through: :languages_texts
  has_many :text_sections

  accepts_nested_attributes_for :authors, allow_destroy: true
  accepts_nested_attributes_for :missionary_group, allow_destroy: true
  accepts_nested_attributes_for :publishers, allow_destroy: true
  accepts_nested_attributes_for :text_category, allow_destroy: true


  scope :title, -> (title) { where('upper(title) like ?', "#{title.upcase}%") }
  scope :author, -> (author) { joins(:authors).where('concat_ws(\' \', upper(authors.first::text), upper(authors.last::text)) like ?', "%#{author.upcase}%") }
  scope :author_id, -> (id) { joins(:authors).where('authors.id = ?', id) }
  scope :missionary_group, -> (id) { joins(:missionary_group).where('missionary_groups.id = ?', id) }

  def hathi_output_url
    if hathi_url and hathi_url.include?('http')
      return hathi_url
    else
      return false
    end
  end

  def google_books_output_url
    if google_url and google_url.include?('http')
      return google_url
    else
      return false
    end
  end

  def structure
    self.text_sections.where('parent_id IS NULL').first.get_json_renderable
  end
end

app/controllers/texts_controller.rb
require 'set'
require 'json'

class TextsController < ApplicationController
  layout 'read', only: [:show, :search]

  def index
    @page = 'texts'
    @texts = build_text_results
  end

  def new
    @text = Text.new
    @flags = @text.attributes.keys.sort
    render 'edit'
  end

  def create
    @text = Text.new()
    if @text.save
      @text.update_attributes(text_params)
      flash[:text_id] = @text.id
      redirect_to controller: 'texts', action: 'index'
    else
      render :action => 'new'
    end
  end

  def destroy
    Text.find(params[:id]).destroy
    flash[:success] = 'text deleted'
    redirect_to controller: 'texts', action: 'index'
  end

  def edit
    @text = Text.find(params[:id])
    @flags = @text.attributes.keys.sort
  end

  def show
    @text = Text.find(params[:id])
    @search_string = params['q']
    @pages = []
    @total = 0
    es = SearchIndex.new
    es.search_pages params['q'], [], params['id']
    puts es.hits
    if (es.hits[:hits] > 0)
      @total =
      @pages = es.hits[:items][0][:pages][:page_hits]
    end

    @page_json = @pages.to_json.html_safe

    respond_to do |format|
      format.html {}
      format.json {self.structure}
    end

  end

  def show_json
    @text = Text.find(params[:id])
    render :json => @text,
           :include => {:missionary_group => {:only => [:name, :id]},
                        :text_category => {:only => [:name, :id]},
                        :publishers => {:only => [:name, :id]},
                        :authors => {
                            :only => [:last, :first]
                        },
                        :languages => {:only => [:designation, :id]}
           },
           :except => [:digital_copy_url, :missionary_group_id, :google_url, :hathi_url, :created_at, :updated_at, :holding_library, :holding_details]
  end

  def read
    @text = Text.find(params[:id])
    @text_json = {:title => @text.title, :authors => @text.authors}.to_json.html_safe
  end

  def structure
    @text = Text.find(params[:id])

    languages = []
    @text.languages.each do |lang|
      languages.push({
                         :id => lang.id,
                         :glottocode => lang.glottocode,
                         :iso => lang.iso,
                         :designation => lang.designation,
                         :alternate_designations => lang.alternate_designations,
                         :macro_classification => lang.macro_classification,
                         :orthography => lang.orthography,
                         :status => lang.status,
                         :latitude => lang.latitude,
                         :longitude => lang.longitude,
                         :location => lang.location
                     })
    end

    render json: {
        :title => @text.title,
        :category => TextCategory.find(@text.text_categories_id).name,
        :authors => @text.authors,
        :year => @text.publication_year,
        :place => @text.publication_place,
        :publisher => @text.publishers,
        :languages => languages,
        :first_page => @text.cover_image.to_i,
        :pages => @text.pages - 1,
        :flags => {
            :by_same_author => @text.by_same_author_flag,
            :preface => @text.preface_flag,
            :foreward => @text.foreward_flag,
            :table_of_prefixes => @text.table_of_prefixes_flag,
            :introduction => @text.introduction_flag,
            :alphabet => @text.alphabet_flag,
            :orthography => @text.orthography_flag,
            :notize => @text.notize_flag,
            :prounciation => @text.prounciation_flag,
            :orthography_and_pronunciation => @text.orthography_and_pronunciation_flag,
            :observations => @text.observations_flag,
            :grammatical_sketch => @text.grammatical_sketch_flag,
            :grammar_summary => @text.grammar_summary_flag,
            :rules_of_language => @text.rules_of_language_flag,
            :phrase_collection => @text.phrase_collection_flag,
            :signs_and_abbreviations => @text.signs_and_abbreviations_flag,
            :abbreviations => @text.abbreviations_flag,
            :sodality => @text.sodality_flag,
            :bulletin => @text.bulletin_flag,
            :proper_names => @text.proper_names_flag,
            :appendix => @text.appendix_flag,
            :addenda => @text.addenda_flag,
            :contents => @text.contents_flag
        },
        :structure => @text.structure
    }
  end

  def update
    @text = Text.find(params[:id])
    @text.update_attributes(text_params)
    redirect_to action: :show, id: @text.id
  end

  def search
    es = SearchIndex.new
    es.search_texts params['title'], params['author'], params['language'], params['publisher'], params['group'], params['date'], params['category'], params['alternate_designations']
    response = {
        :language => es.languages,
        :alternate_designations => es.alternate_designations,
        :title => es.titles,
        :author => es.authors,
        :publisher => es.publishers,
        :date => es.dates,
        :category => es.categories,
        :hits => es.hits
    }
    respond_to do |format|
      format.html {}
      format.json {render json: response}
    end
  end

  def searchpages
    es = SearchIndex.new
    es.search_pages params['q'], [], params['id']
    response = {
        :language => es.languages,
        :alternate_designations => es.alternate_designations,
        :title => es.titles,
        :author => es.authors,
        :publisher => es.publishers,
        :date => es.dates,
        :category => es.categories,
        :hits => es.hits
    }
    respond_to do |format|
      format.html {}
      format.json {render json: response}
    end
  end

  private

  def build_select_list(base_class, order_sql, value_field, param_symbol)
    response = []
    response = base_class.order(order_sql).all.map {|item| {label: item.send(value_field), value: item.id}}
    return response
  end

  def build_text_results
    texts = Text.order('title ASC').where(nil)
    texts = texts.title(params[:title]) if params[:title].present?
    texts = texts.author_id(params[:authors]) if params[:authors].present?
    texts = texts.missionary_group(params[:groups]) if params[:groups].present?
    return texts
  end

  def build_api_result(text)
    result = {}
    result['title'] = text.title
    result['id'] = text.id
    result['authors'] = text.authors.select('id')
    result['publishers'] = text.publishers.select('id')
    result['groups'] = text.missionary_group
    return result
  end

  def extract_field(result)

  end

  def text_params
    params.require(:text).permit(:title, {:author_ids => []}, {:language_ids => []}, {:publisher_ids => []}, :text_category_id, :missionary_group_id, :publication_year, :edition_node, :publication_place, :publisher, :holding_library, :holding_details, :digital_copy_url, :hathi_url, :google_url, :text_categories, :by_same_author_flag, :preface_flag, :foreward_flag, :table_of_prefixes_flag, :introduction_flag, :alphabet_flag, :orthography_flag, :notize_flag, :prounciation_flag, :orthography_and_pronunciation_flag, :observations_flag, :grammatical_sketch_flag, :grammar_summary_flag, :rules_of_language_flag, :phrase_collection_flag, :signs_and_abbreviations_flag, :abbreviations_flag, :sodality_flag, :bulletin_flag, :proper_names_flag, :appendix_flag, :addenda_flag, :contents_flag,)
  end

end

app/helpers/texts_helper.rb
module TextsHelper
  def form_fieldset(fieldset_label, form, field, attribute)
    render "texts/form_fieldset", fieldset_label: fieldset_label, form: form, field: field, form_element: attribute
  end

  def form_line(form, field, input_type)
    render 'texts/form_line', form: form, field: field, input_type: input_type
  end
end

app/views/texts/_authors_texts_fields.html.erb
<div class='nested-fields author'>
  <div id="author_from_list">
    <%= f.association :author, :collection =>
  </div>
</div>

app/views/texts/_form_fieldset.html.erb
<fieldset>
  <legend><%= fieldset_label %></legend>
  <%= form.fields_for field do |subform| %>
      <dt><%= subform.label form_element %></dt>
      <dd><%= subform.text_field form_element %></dd>
  <% end %>
</fieldset>

app/views/texts/_form_line.html.erb
<dt><%= form.label field %></dt>
<dd><%= form.method(input_type).call field %></dd>

app/views/texts/_old_edit.html.erb
<h2><cite><%= @text.title %></cite></h2>

<% if @text.id == 13 %>
    <a href="/texts/13/read/">read</a>
<% end %>

<div class="text">
  <div class="metadata">

    <%= form_for @text do |f| %>

        <h3>Metadata</h3>

        <%= form_line(f, :title, 'text_area') %>

        <dt>Authors</dt>
        <dd>
          <%= collection_select :text, :author_ids, Author.order('last ASC'), :id, :full_name, {:selected => @text.author_ids}, {:multiple => true, :name => 'text[author_ids][]'} -%>
        </dd>

        <dt>Missionary group</dt>
        <dd>
          <%= collection_select :text, :group_ids, MissionaryGroup.order('name ASC'), :id, :name, {:selected => @text.missionary_group_id}, {:multiple => false, :name => 'text[missionary_group_id]'} -%>
        </dd>

        <dt>Publishers</dt>
        <dd>
          <%= collection_select :text, :publisher_ids, Publisher.order('name ASC'), :id, :name, {:selected => @text.publisher_ids}, {:multiple => true, :name => 'text[publisher_ids][]'} -%>
        </dd>

        <%= form_line(f, :publication_year, 'text_field') %>
        <%= form_line(f, :publication_place, 'text_field') %>
        <%= form_line(f, :edition_note, 'text_area') %>



        <fieldset>
          <legend>Holdings</legend>
          <%= form_line(f, :holding_library, 'text_field') %>
          <%= form_line(f, :holding_details, 'text_field') %>
          <%= form_line(f, :digital_copy_url, 'text_field') %>
          <%= form_line(f, :google_url, 'text_field') %>
          <%= form_line(f, :hathi_url, 'text_field') %>
        </fieldset>

        <fieldset>
          <legend>Flags</legend>
          <% @flags.each do |attr_name| %>
              <% if attr_name.include? '_flag' %>
                  <%= form_line(f, attr_name, 'check_box') %>
              <% end %>
          <% end %>
        </fieldset>

          <%= submit_tag("Update") %>

    <% end %>
  </div>
  <div class="languages">
    <h3>Languages</h3>
    <ul>
      <% @text.languages.each do |language| %>
          <li><%= link_to language.designation, language_path(language) %></li>
      <% end %>
    </ul>

  </div>

</div>

app/views/texts/create.html.erb
<h1>Texts#create</h1>
<p>Find me in app/views/texts/create.html.erb</p>

app/views/texts/destroy.html.erb
<h1>Texts#destroy</h1>
<p>Find me in app/views/texts/destroy.html.erb</p>

app/views/texts/edit.html.erb
<h2><cite><%= @text.title %></cite></h2>

<% if @text.id == 13 %>
    <a href="/texts/13/read/">read</a>
<% end %>

<div class="text">
  <div class="metadata">
    <%= simple_form_for @text do |f| %>
        <%= f.input :title, :as => :text %>

        <div class="input">
          <label>Languages</label>
          <%= collection_select :text, :language_ids, Language.order('designation ASC'), :id, :designation, {:selected => @text.language_ids}, {:multiple => true, :name => 'text[language_ids][]'} -%>
        </div>

        <div class="input">
          <label>Authors</label>
          <%= collection_select :text, :author_ids, Author.order('last ASC'), :id, :full_name, {:selected => @text.author_ids}, {:multiple => true, :name => 'text[author_ids][]'} -%>
        </div>

        <%= f.association :missionary_group, label_method: :name %>
        <%= f.association :publishers, collection: Publisher.order('name ASC'), label_method: :name %>
        <%= f.input :publication_year, :as => :string %>
        <%= f.input :publication_place, :as => :string %>
        <%= f.input :edition_note %>
        <%= f.input :holding_library, :as => :string %>
        <%= f.input :holding_details, :as => :string %>
        <%= f.input :digital_copy_url, :as => :string %>
        <%= f.input :google_url, :as => :string %>
        <%= f.input :hathi_url, :as => :string %>

        <%= f.association :text_category, collection: TextCategory.order('name ASC'), label_method: :name %>


        <h3 class="flags">Flags</h3>

        <% @flags.each do |attr_name| %>
            <% if attr_name.include? '_flag' %>
                <%= f.input attr_name %>
            <% end %>
        <% end %>

        <%= f.submit 'Save' %>

    <% end %>
  </div>

  <div class="languages">
    <h3>Languages</h3>
    <ul>
      <% @text.languages.each do |language| %>
          <li><%= link_to language.designation, language_path(language) %></li>
      <% end %>
    </ul>
  </div>

</div>

app/views/texts/index.html.erb
<%= content_for :header do %>Texts<% end %>

<ul class="text-list">
  <% @texts.each do |text| %>
      <li>
        <%= link_to text do %>
            <div class="cover-holder">
              <img src="/img/texts/<%= text.id %>/cover-small.jpg" alt="cover image">
            </div>
            <cite><%= text.title %></cite>
        <% end %>
        <% if logged_in? %>
            <%= link_to 'delete', text_path(text.id), :method => :delete, :class => 'delete', :confirm => 'Are you sure ?' %>
        <% end %>
      </li>
  <% end %>
</ul>

<% if logged_in? %>
    <%= link_to '+ New text', :controller => :texts, :action => :new %>
<% end %>

app/views/texts/new.html.erb
<h1>Texts#new</h1>
<p>Find me in app/views/texts/new.html.erb</p>

app/views/texts/search.html.erb
<div class="center-content">
  <div id="search-holder"></div>
</div>

app/views/texts/show.html.erb
<script>
    var page_data = <%= @page_json %>;
</script>
<div class="center-content">
  <div id="reader" data-react-props="<%= @text.id %>" data-search-string="<%= @search_string %>" data-page-result="<%= @page_json %>"></div>
</div>

app/views/texts/update.html.erb
<h1>Texts#update</h1>
<p>Find me in app/views/texts/update.html.erb</p>